const fs = require('fs')
const path = require('path')
const vm = require('vm')
const chalk = require('chalk')
//const stableParser = require('../parser')
const stableParser = require('./parser')
const ws = require('ws')
//require('caught')
//log('build new parser')
let new_parser_code = fs.readFileSync('parser.ws', 'utf8')
log('parse parser')
//log('new parser ws code');log(new_parser_code)
//let new_ast = stableParser.parse('../parser.ws',  new_parser_code)
let new_ast = stableParser.parse('parser.ws',  new_parser_code)
//log('new parser ws code ast');log(new_ast)
log('unparse parser')
let code = stableParser.unparse(new_ast).code
//log('new parser js code');log(code)
fs.writeFileSync('parser.new.js', code)
log('load parser')
//let new_parser = require('../parser.new.js')
let new_parser = require('./parser.new.js')
ws.replaceParser(new_parser)
//let result = ws.run('build/test.ws')
let result = ws.run('test.ws')
log('result', result)
if (result === true) {
  log('test passed')
  process.exit(123)
} else {
  log(chalk.red('test failed'))
  process.exit(1)
}
